### PR TITLE
Refactor commands system + Small actor stuff again

### PR DESCRIPTION
**Pull request by morgana-x**
+ Refactor commands
+ RemoveActor Utility method for Spawner.cs
+ Add ChatUtils.cs

Once again I do not have two accounts setup, but have been able to test commands using the console

Would need some testing to verify the current admin/permission config system works

The changes to Spawner.cs regarding the utilisation of the new RemoveActor method may also need to be verified in-game

### CODE REVIEW

**Comment by ncrypted-dev** [comment]
Thanks a lot for the awesome Rework/PR! I don't if I'll be able to review everything today, but I will merge it as soon as possible!

**Comment by ApexDevelopment** [comment]
This would be awesome. I was thinking about doing the exact same thing when I was adding the !stop command. I'll rework that PR if this is merged.

**Comment by morgana-x** [comment]
So sorry for another commit, just realised I had completely ignored the fact that there was already a spot for admins in config.toml, and have adjusted the command system to use that instead of an admins.txt file (Although might switch back to admins.txt later if more convenient)

I also just added a setadmin/revokeadmin command that temporarily sets a player to admin / revokes it (Useable by console only)

The only thing stopping the admin set from not being temp is the config system, which doesn't provide flexibility to save the config again unfortunately as of right now, maybe that could be the focus of a future refactor later

Also realised I had some command classes set to public instead of internal which I changed promptly

Also fixed some silly midnight mistakes regarding some stuff in Spawner.cs I changed

**Comment by ncrypted-dev** [comment]
@morgana-x Thanks for the fixes - I had already fixed most of them in my local copy of the PR anyways, so no worries ;) 
I was able to test most of the new features yesterday evening, so I will merge this PR later today.

**Pull request merged**
