### PR TITLE
Switch to using an enum for actor types

### PR DESCRIPTION
**Pull request by ApexDevelopment**
If the name of a type of actor is ever changed, we would have to comb the codebase to update the string constant we use for it everywhere. An enum avoids that problem.

I have not thoroughly tested this change (not at my main PC right now) so it would be best to boot it up and make sure that spawning still works properly before merging, I just wanted to put this on your radar.

Serializing the enum so that it can be sent in a `SpawnActorPacket` is just done through `ToString().ToLower()`. The enum values should match their canonical Webfishing GDScript counterparts, but it could probably use double-checking.

This change also supports merging all of the `Spawner` static spawning methods together in the future (not this PR).

### CODE REVIEW

**Comment by ncrypted-dev** [comment]
Thanks, I will review and test the changes tomorrow evening!

**Comment by morgana-x** [comment]
I think there are more actor types then what is listed in the enum table however, like props and tents etc. In which case this enum table could potentially be quite limiting or exhaustive to update, I'd recommend checking a dump of Webfishing and navigating to Scenes\Entities. While most are not networked there's still a few that presumably are and not in the enum table

Perhaps it would be best to keep the arguments for Actor initialization and SpawnActor as strings, and then use the enum ToString() as convention unless all networked actor types are added to the enum table

Just to avoid limiting the capabilities of using actors in extensions or otherwise

**Comment by ApexDevelopment** [comment]
@morgana-x 
> I think there are more actor types then what is listed in the enum table however, like props and tents etc. In which case this enum table could potentially be quite limiting or exhaustive to update

Keeping string constants across the codebase would be even more exhaustive to update. Say lamedeveloper adds a new weather phenomenon. Now, everywhere we want to reference that new weather phenomenon, we have to add a new string constant (see e.g. the way "raincloud" is scattered across 4 or 5 places). Whereas with an enum (and unified `Spawner` functions) we don't have that, we only update one line of code.

I left a comment in my code about mapping the enum to strings that match the canonical names of the actor types. This solution would be even more ideal, as any time we need to convert from string to enum or vice versa (think parsing the !spawn command for example) it would just be a simple function call, no messing around with more constants which are prone to typos and being forgotten if/when those names change in Webfishing's code.

**Comment by morgana-x** [comment]
True, but for the cases where the actortype is not supported and thus say a hypothetical extension developer would have to wait for the server to update the enums

I'd say stick to enums for the main server code, but leave an option for extension developers to use string types when they need to

perhaps we could leave in the string argument version of the Spawn Actor methods by something like:
```cs
public static Actor SpawnActor(ActorType Type,...)
{
		return SpawnActor(Type.ToString(),...);
}
public static Actor SpawnActor(string Type,...)
{
...
}
```

And perhaps keeping the Type field in the Actor class as a string, then have two constructor methods

One being
```cs
public Actor(ActorType type, ....)
{
 Type = type.ToString()
}
```
the other
```cs
public Actor(string type)
{
Type = type
}
```

Therefor, the enums can still be used as the primary method of defining the type of the entity for the actual server code, however noone is limited to those enums if they wanted to use something that isn't defined in the enums externally in say a plugin environment

Granted it causes the code to be a little bit more bloated but could be an inbetween solution perhaps maybe

**Comment by ApexDevelopment** [comment]
@morgana-x 

I think this is an ok compromise. I decided to go ahead and consolidate all the spawning functions into one. That will be one commit, then the next commit will be adding the string-based alternatives.

**Comment by ApexDevelopment** [comment]
Nevermind, it's too tangled to do in two separate commits. One commit coming up.

**Comment by ApexDevelopment** [comment]
These commits make the code much DRYer. I think it's a huge tidy-up.

**Pull request merged**
